### ISSUE TITLE
Create a configuration tool for RepRap firmware [$50]

### ISSUE THREAD

**Issue by bobc** [bobc/RepRap-meta-proto#1]
Problem:

To configure a RepRap for a particular printer, users have to edit a C header file. This can be tricky and error prone. Some firmwares allow a config file to be stored on an SD card, but the file still needs editing by hand.

Required

A user friendly config tool. The tool should be allow the user to select config settings, and then export the settings to a C header file, or other text file.

The tool should be cross-platform, at least Windows, Unix. The tool can store a local database of settings in a format such as XML, it does not need to read and parse a C header file, although that would be nice at least for initial import.

The tool may be written in any suitable language such as Python, Java, C#. The project must be published with a GPL or other Open Source license.
##

**Comment by jeffrey-elliott** [comment]
This sort of thing seems extremely doable from a data perspective. Are all the possible values known ahead of time? Is there an easy pointer an example header?

**Comment by mattmoses** [comment]
There are a lot of different firmwares out there, but I think a decent representative example is Marlin. The configuration file is called "Configuration.h" and you can find an example here: https://github.com/ErikZalm/Marlin/blob/Marlin_v1/Marlin/Configuration.h

**Comment by SamP20** [comment]
I'm currently working on a solution in python. I have two options I'm working with for loading the GUI for different firmwares, and need help deciding which to use. The options are an XML file or a python script. The python script is easier to write than the XML, and is more flexible. The downside is that it isn't very safe if users start using scripts from external sources. Which option would you recommend?

Edit: I've made a decision to keep to XML for now. It's flexible enough for this purpose.

**Comment by SamP20** [comment]
Just something to whet your appetite:
![image](https://cloud.githubusercontent.com/assets/633856/2925501/f5649dc2-d74c-11e3-8de1-272bc2d36ccd.png)
The gui is very similar to Slic3r, and is generated from an XML file. I've currently implemented Text, Integer, Real (floating point), and Choice inputs. They also support tooltips.

I'm a little reluctant to post source code straight away since I'm a bit concerned someone else could take what I've started and finish it themselves to claim the bounty without putting the full work into it. Please persuade me otherwise if you disagree.

**Comment by SamP20** [comment]
More progress:
![image](https://cloud.githubusercontent.com/assets/633856/2937388/743624c4-d89f-11e3-8602-67927b254e03.png)
Moved back to using .py scripts since I hit a bit of a wall with the XML files. Sections of the GUI can be hidden depending on other options. For example in the image above the "Kinematic Configuration" will switch the StaticBox between Cartesian, Delta and CoreXY. For this behaviour I allowed the use of lambdas or functions in place of constants. e.g.

``` python
GP.OptionsGroup("CoreXY", visible=GP.Func(["KINEMATIC_CONFIG"], lambda val: val==1))
```

I think hardest of the GUI stuff is done now. The next challenge is formatting the output file(s). A templating module such as http://code.activestate.com/recipes/576663-templite/ should be a good starting point.

**Comment by mattmoses** [comment]
Has anyone been working on this? Does [Teacup Configtool](http://forums.reprap.org/read.php?1,516185) meet the requirements for this bounty?

**Comment by Traumflug** [comment]
> Does Teacup Configtool meet the requirements for this bounty?

I think so. Configtool doesn't use XML storage, it stores in header files directly to maintain compatibility with command line and Arduino IDE. While Configtool can build and upload, it doesn't break the other approaches.

It's all GUI, no external text editor, no touching of the command line neccessary. Best of it: it apparently works for quite some people, people started talking about it. Works on Mac OS X, Linux, Windows by using Python2 and a matching wxPython. Compile and upload tool are provided by the environment or by Arduino IDE unpacked somewhere.

**Comment by Traumflug** [comment]
Ah, pictures are usually welcome :-) Here is one:

![teacup configtool](https://cloud.githubusercontent.com/assets/318581/8696942/31885f70-2af1-11e5-9a3c-ebfc308211d2.png)

**Comment by bobc** [comment]
Teacup Configtool looks fantastic! I had a quick play and it does just what I imagined, it is simple to use and looks good too.

I would be happy to award the bounty, to claim it will the claimant just close this issue, preferably with a link to the source repo and any other useful links.

Thanks and great work!

**Comment by mattmoses** [comment]
> I would be happy to award the bounty, to claim it will the claimant just close this issue, preferably with a link to the source repo and any other useful links.

I am not certain about this, but I think @bobc is the only one who can close the issue. Once the issue is closed here, the claimant (for example @jbernardis) can claim the bounty on Bountysource. Then, once the backers (@bobc) approve the claim, the claimant receives the funds.

**Comment by jbernardis** [comment]
I was wondering about this.  I was looking over on bobc's github and I saw
no way for me to close the issue.

**Comment by jbernardis** [comment]
@bobc 

As per the discussion above, I am claiming the bounty for the Teacup configuration tool.  There is no separate repository; it is part of the teacup repo located here: [https://github.com/Traumflug/Teacup_Firmware](https://github.com/Traumflug/Teacup_Firmware)

As mentioned above, I see no way myself to close this issue.  What is the next step I need to take to move this forward?

Thanks
Jeff
@jbernardis

**Comment by bobc** [comment]
I didn't realise this was not closed yet. The code at https://github.com/Traumflug/Teacup_Firmware/tree/master/configtool meets all the requirements of the bounty, so I have marked the issue "Fixed" and will close the issue.
